apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-eures-stilling-import
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 9026
  liveness:
    path: /pam-eures-stilling-import/internal/isAlive
    initialDelay: 20
  readiness:
    path: /pam-eures-stilling-import/internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 4
  cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: false
  webproxy: true
  prometheus:
    enabled: true
    path: /pam-eures-stilling-import/internal/actuator/prometheus
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  accessPolicy:
    outbound:
      external:
        - host: ec-europa.eu
          ports:
            - port: 443
              name: https
              protocol: HTTPS
