apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-eures-stilling-import
  namespace: default
  labels:
    team: teampam
spec:
  image: {{ image }}:{{ tag }}
  port: 9026
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  liveness:
    initialDelay: 20
    path: /euresapi/internal/isAlive
  readiness:
    initialDelay: 20
    path: /euresapi/internal/isAlive
  prometheus:
    enabled: true
    path: /euresapi/internal/actuator/prometheus
  webproxy: true
  ingresses:
  - https://pam-eures-stilling-import.nais.oera.no
  - https://tjenester.nav.no/pam-eures-stilling-import
