server:
  port: 9026
spring:
  main:
    banner-mode: off
management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["prometheus", "metrics"]
      base-path: /euresapi/internal/actuator

shouldUseProxy: true
ProxyUrlHostName: webproxy-internett.nav.no
ProxyUrlPort: 8088
ProxyUrlScheme: HTTP

